### ISSUE TITLE
Example code seems to generate corrupted MP3

### ISSUE THREAD

**Issue by ValonVN0** [supersu-man/pyt2s#6]
Hello again,

Got the module updated and in the process of getting things rewritten to account for the changes, but I'm finding that even when using the example code on the main page it's generating mp3s which don't actually seem to play.

Now it's not throwing any errors, in fact the only actual error I'm getting is from another module I use to read the mp3 data which is what tipped me off to it being corrupted somehow.

Sure enough, I played the mp3 itself manually (via VLC in my case) and nothing, Media Player suggests it's missing info is is corrupted somehow though I'm not getting any errors to help track it down.

I'll keep testing to see if I can get some form of stacktrace but hopefully that's a slight help to start with.

**Comment by ValonVN0** [comment]
Update: This issue occurs when using the "Custom Voice" section, however the default voice works perfectly fine.

**Comment by ValonVN0** [comment]
Additional Update: Just used a snippet from streamlabs.py itself to run the request post manually and it works without issue when just entering the params manually, so I'm really stumped on that one.

**Comment by ValonVN0** [comment]
```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\Proton Drive\xxx\My files\projects\current\programming\vayl\vayl.py", line 1154, in runActions
    data = streamlabs.requestTTS('Lorem Ipsum is simply dummy text.', streamlabs.Voice.Ivy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyt2s\services\streamlabs.py", line 78, in requestTTS
    mp3_url = res.json()['speak_url']
              ^^^^^^^^^^
  File "C:\Users\joene\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
Okay, managed to get this stacktrace when testing some other voice packs, of course streamlabs is imported from the module and referenced as "streamlabs"

**Comment by supersu-man** [comment]
Apologies for the bad documentation. Use `streamlabs.Voice.Ivy.value` instead `streamlabs.Voice.Ivy`.
